// contentData.js
// Data untuk konten bagian
const contentData = [
    {
        id: 1,
        title: "Mengapa Harus Belajar di New Primagama Fatmawati",
        imgSrc: "/images/buku.png",
        imgAlt: "Robot Zenius",
        heading: "Tes Minat Bakat (Tes Diagnostik)",
        text: "Tes yang dilakukan untuk memastikan putra/i kita belajar sesuai dengan gaya dan modalitas belajarnya masing-masing.",
        aosImage: "fade-right",
        aosText: "fade-left",
    },
    {
        id: 2,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Akses Premium ke zenius.net",
        text: "Siswa dapat mengakses puluhan ribu video materi, latihan soal, dan pembahasan.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 3,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Gratis Konsultasi Setiap Hari",
        text: "Siswa yang terkendala untuk memahami materi ataupun tugas yang diberikan oleh guru di sekolah, dapat meminta sesi konsultasi secara gratis.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 4,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Kelas Zen-Core",
        text: "Skill dan knowledge dasar (fundamental skills) yang harus dikuasai oleh semua orang terlepas dari apa pun jenjang pendidikan, jurusan, atau bidang kerjaannya.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 5,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Buku dan Proset Super Lengkap",
        text: "Buku fase, master book, smart exercise, dan proset yang sudah disesuaikan dengan kurikulum pemerintah dan mudah dipahami.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 6,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Professional Tutor",
        text: "Disiapkan tim pengajar yang handal, terlatih, berpengalaman, dan mampu menyampaikan materi dengan cara yang asik, interaktif dan menyenangkan.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 7,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "One Day Before Exam",
        text: "Program Super Intensif masuk setiap hari selama persiapan ATS, AAS, ASTS, ASAT, dan UTBK sampai Ujian Mandiri 2025 dilengkapi dengan Try Out dan drilling ribuan soal secara berkala.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 8,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Kelas Motivasi Juara dan Self Improvement",
        text: "Kelas untuk membekali siswa/i dalam menghadapi ujian akhir dengan mental positif dan motivasi yang kuat.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 9,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Sarana dan Prasarana Belajar yang Baik",
        text: "Kelas yang kondusif (maksimal 12 siswa/kelas) dan nyaman yang sudah dilengkapi dengan AC, TV, whiteboard, dan CCTV.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 10,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Komunitas Zen-Sport dan Ekskul English",
        text: "Zen-Sport diadakan setiap bulannya agar siswa/i dapat merefresh otak setelah belajar. Ekskul Bahasa Inggris diadakan untuk melatih basic skills siswa/i.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
    {
        id: 11,
        imgSrc: "/images/Generasiemas.png",
        imgAlt: "Generasi Emas",
        heading: "Analisa Nilai Raport",
        text: "Sistem konsultasi terpadu untuk menganalisa tingkat keberhasilan siswa dalam proses belajar ke terutama tingkat selanjutnya,terutama untuk memaksimalkan peluang jalur SNBP 2025.",
        aosImage: "fade-left",
        aosText: "fade-right",
    },
];

export default contentData;
